# Generated by Django 4.2.5 on 2023-10-17 19:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="City",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=55)),
                ("postal_code", models.CharField(max_length=10)),
            ],
            options={
                "verbose_name_plural": "cities",
            },
        ),
        migrations.CreateModel(
            name="District",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name="Listing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "advertizer_type",
                    models.CharField(
                        choices=[("owner", "Owner"), ("agent", "Agent")],
                        default="owner",
                        max_length=10,
                    ),
                ),
                (
                    "offer_type",
                    models.CharField(
                        choices=[("sale", "Sale"), ("rent", "Rent")],
                        default="sale",
                        max_length=10,
                    ),
                ),
                (
                    "property_type",
                    models.CharField(
                        choices=[
                            ("house", "House"),
                            ("apartment", "Apartment"),
                            ("bungalow", "Bungalow"),
                            ("villa", "Villa"),
                            ("annexe", "Annexe"),
                            ("rooms", "Rooms"),
                            ("studio", "Studio"),
                        ],
                        default="house",
                        max_length=10,
                    ),
                ),
                ("address_no", models.CharField(max_length=10)),
                ("address_1", models.CharField(max_length=55)),
                ("address_2", models.CharField(max_length=55)),
                ("postal_code", models.CharField(max_length=10)),
                ("bedrooms", models.IntegerField()),
                ("bathrooms", models.IntegerField()),
                ("floor_area", models.IntegerField()),
                ("land_area", models.IntegerField(blank=True, null=True)),
                (
                    "land_area_unit",
                    models.CharField(
                        blank=True,
                        choices=[("perches", "Perches"), ("acres", "Acres")],
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "furnishing_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("unfurnished", "Unfurnished"),
                            ("basic_furnished", "Basic Furnished"),
                            ("modern_furnished", "Modern Furnished"),
                            ("fully_furnished", "Fully Furnished"),
                            ("custom_furnished", "Custom Furnished"),
                        ],
                        max_length=25,
                        null=True,
                    ),
                ),
                ("price", models.IntegerField()),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("main_photo", models.ImageField(upload_to="images/")),
                (
                    "photo_1",
                    models.ImageField(blank=True, null=True, upload_to="images/"),
                ),
                (
                    "photo_2",
                    models.ImageField(blank=True, null=True, upload_to="images/"),
                ),
                (
                    "photo_3",
                    models.ImageField(blank=True, null=True, upload_to="images/"),
                ),
                (
                    "photo_4",
                    models.ImageField(blank=True, null=True, upload_to="images/"),
                ),
                (
                    "photo_5",
                    models.ImageField(blank=True, null=True, upload_to="images/"),
                ),
                (
                    "photo_6",
                    models.ImageField(blank=True, null=True, upload_to="images/"),
                ),
                ("is_published", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "modified_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "advertizer",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "city",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="listings.city"
                    ),
                ),
                (
                    "district",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="listings.district",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="city",
            name="district",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="listings.district"
            ),
        ),
    ]
