# Generated by Django 4.2.5 on 2023-10-17 23:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("listings", "0002_alter_listing_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="listing",
            name="description",
            field=models.TextField(max_length=3000),
        ),
    ]
