# Generated by Django 4.2.5 on 2023-10-18 21:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("listings", "0004_alter_city_options_alter_listing_floor_area_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="listing",
            name="advertizer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="listings",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
