# Generated by Django 4.2.5 on 2023-10-19 16:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("listings", "0006_alter_listing_is_published"),
    ]

    operations = [
        migrations.AlterField(
            model_name="listing",
            name="bathrooms",
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name="listing",
            name="is_published",
            field=models.BooleanField(
                default=False,
                help_text="Please review your listing details for accuracy before publishing. Ensure all information is complete and correct. Thank you.",
            ),
        ),
        migrations.AlterField(
            model_name="listing",
            name="land_area",
            field=models.IntegerField(blank=True, default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="listing",
            name="land_area_unit",
            field=models.CharField(
                blank=True,
                choices=[("perches", "Perches"), ("acres", "Acres")],
                default=1,
                max_length=10,
            ),
            preserve_default=False,
        ),
    ]
