# Generated by Django 4.2.5 on 2023-10-22 09:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("listings", "0010_listing_phone_number_alter_listing_is_published"),
    ]

    operations = [
        migrations.AlterField(
            model_name="listing",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="listing",
            name="modified_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
