# Generated by Django 4.2.5 on 2023-10-08 08:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="last_name",
            field=models.CharField(max_length=150, verbose_name="Last Name"),
        ),
    ]
