# Generated by Django 4.2.5 on 2023-10-12 21:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="username",
            field=models.CharField(max_length=150, verbose_name="Owner"),
        ),
    ]
